# Generated by Django 3.1.6 on 2022-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=80)),
                ('certValid', models.BooleanField(default='False')),
                ('checkFrequency', models.IntegerField(default='86400')),
            ],
        ),
    ]
