# Generated by Django 3.1.6 on 2022-09-13 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certmonitor',
            name='expirationDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
