# Generated by Django 3.1.6 on 2022-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certmonitor',
            name='checkFreqency',
            field=models.IntegerField(default='86400'),
        ),
    ]
